#ifndef BLE_KEYBOARD_ERRORS_H
#define BLE_KEYBOARD_ERRORS_H

// BLE Keyboard Error Codes
#define BLE_KEYBOARD_SUCCESS                0x00
#define BLE_KEYBOARD_ERROR_GENERIC          0x01
#define BLE_KEYBOARD_ERROR_NOT_CONNECTED    0x02
#define BLE_KEYBOARD_ERROR_NOT_INITIALIZED  0x03
#define BLE_KEYBOARD_ERROR_INVALID_PARAM    0x04
#define BLE_KEYBOARD_ERROR_NO_MEMORY        0x05
#define BLE_KEYBOARD_ERROR_TIMEOUT          0x06
#define BLE_KEYBOARD_ERROR_BT_DISABLED      0x07
#define BLE_KEYBOARD_ERROR_ADVERTISING      0x08
#define BLE_KEYBOARD_ERROR_PAIRING          0x09
#define BLE_KEYBOARD_ERROR_HID_DEVICE       0x0A
#define BLE_KEYBOARD_ERROR_CHARACTERISTIC   0x0B

// BLE Connection States
#define BLE_KEYBOARD_STATE_DISCONNECTED     0x00
#define BLE_KEYBOARD_STATE_CONNECTING       0x01
#define BLE_KEYBOARD_STATE_CONNECTED        0x02
#define BLE_KEYBOARD_STATE_ADVERTISING      0x03

// BLE Security Error Codes
#define BLE_KEYBOARD_SEC_ERROR_NONE         0x00
#define BLE_KEYBOARD_SEC_ERROR_PASSKEY      0x01
#define BLE_KEYBOARD_SEC_ERROR_OOB          0x02
#define BLE_KEYBOARD_SEC_ERROR_AUTH_FAIL    0x03
#define BLE_KEYBOARD_SEC_ERROR_CONFIRM      0x04
#define BLE_KEYBOARD_SEC_ERROR_PAIRING_NOTSUPP 0x05
#define BLE_KEYBOARD_SEC_ERROR_ENC_KEY_SIZE 0x06
#define BLE_KEYBOARD_SEC_ERROR_SMP_CMD_NOTSUPP 0x07
#define BLE_KEYBOARD_SEC_ERROR_UNSPECIFIED  0x08
#define BLE_KEYBOARD_SEC_ERROR_REPEATED_ATTEMPTS 0x09
#define BLE_KEYBOARD_SEC_ERROR_INVALID_PARAMS 0x0A

// HID Report Error Codes  
#define BLE_KEYBOARD_HID_SUCCESS            0x00
#define BLE_KEYBOARD_HID_ERROR_INVALID_REPORT_ID 0x01
#define BLE_KEYBOARD_HID_ERROR_UNSUPPORTED_REQUEST 0x02
#define BLE_KEYBOARD_HID_ERROR_INVALID_PARAMETER 0x03
#define BLE_KEYBOARD_HID_ERROR_UNKNOWN      0x0E
#define BLE_KEYBOARD_HID_ERROR_FATAL        0x0F

#endif // BLE_KEYBOARD_ERRORS_H